"""Market Oracle AI — Core Simulation Engine v2

Implements all 7 upgrades:
  1. Programmatic confidence (no LLM-generated confidence score)
  2. Adversarial agent personas: MacroBull / GeoBear / Quant / NeutralFund / Judge
  3. Live market context injection before agents run
  4. Structured 6-field causal chain template (generated by Judge)
  5. prediction_log persistence
  6. Updated PredictionCard schema fields
  7. Correct execution pipeline order

Pipeline order:
  fetch_market_context(ticker)
  → load lessons from prediction_log
  → run 45 adversarial agents in parallel
  → tally votes
  → calculate_confidence() programmatically
  → run Judge agent (sequential)
  → apply confidence modifier
  → Judge generates structured causal chain
  → save to prediction_log
  → return PredictionResponse
"""

import sys
import os
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

if hasattr(sys.stdout, 'reconfigure'):
    sys.stdout.reconfigure(encoding='utf-8', errors='replace')
if hasattr(sys.stderr, 'reconfigure'):
    sys.stderr.reconfigure(encoding='utf-8', errors='replace')

import asyncio
import json
import uuid
import logging
from datetime import datetime
from typing import List, Dict, Any, Optional, Tuple
from dotenv import load_dotenv

load_dotenv()

from llm_router import LLMRouter, parse_json_response
from models.prediction import (
    PredictionCard, DirectionEnum, TimeHorizonEnum,
    KeySignal, SignalType, AgentConsensus, CausalChainStep
)
from event_ticker_mapping import map_event_to_ticker, get_ticker_info

logger = logging.getLogger(__name__)

# ── Configurable agent count ───────────────────────────────────────────────────
NUM_AGENTS = int(os.getenv("NUM_AGENTS", "45"))


# ═══════════════════════════════════════════════════════════════════════════════
# UPGRADE 1 — Programmatic confidence calculation
# ═══════════════════════════════════════════════════════════════════════════════

def calculate_confidence(bullish: int, bearish: int, neutral: int) -> float:
    """
    Calculate real confidence based on agent vote variance.
    Replaces LLM-generated confidence entirely.

    Returns a 0.0–1.0 float (Pydantic model-compatible).

    Quality check:
      24 bearish / 0 bullish / 26 neutral → ~23%  ✓
    """
    total = bullish + bearish + neutral
    if total == 0:
        return 0.0

    # Base consensus: polarisation of non-neutral agents
    base = abs(bearish - bullish) / total

    # Neutral penalty: undecided market = lower confidence
    neutral_ratio = neutral / total
    confidence = base * (1 - neutral_ratio)

    # Hard cap: >40% neutral → market undecided → cap at 60%
    if neutral_ratio > 0.40:
        confidence = min(confidence, 0.60)

    return round(confidence, 3)


# ═══════════════════════════════════════════════════════════════════════════════
# UPGRADE 2 — Adversarial agent persona definitions
# ═══════════════════════════════════════════════════════════════════════════════

_NEWS_PRIORITY_RULE = (
    "NEWS PRIORITY RULE (mandatory):\n"
    "CRITICAL signals override all other signals. If a CRITICAL news item exists, build your analysis around it first.\n"
    "LOW signals must not be used as primary reasoning — they can only appear as supporting context.\n"
    "If CRITICAL and LOW signals point in opposite directions, always side with the CRITICAL signal.\n"
)

_BROAD_MARKET_RULE = (
    "BROAD MARKET RULE (mandatory):\n"
    "If market_session = BROAD_SELLOFF: you need strong company-specific BULLISH evidence (CRITICAL-rated news) "
    "to justify a bullish vote. Without it, default to bearish or neutral.\n"
    "If market_session = BROAD_RALLY: you need strong company-specific BEARISH evidence (CRITICAL-rated news) "
    "to justify a bearish vote. Without it, default to bullish or neutral.\n"
    "If market_session = FLAT or UNKNOWN: use normal analysis, no bias.\n"
)

_VOLUME_RULE = (
    "VOLUME INTERPRETATION RULE (mandatory):\n"
    "Volume MUST be read alongside price direction — never in isolation.\n"
    "HIGH volume + price DOWN = institutional DISTRIBUTION = BEARISH signal.\n"
    "HIGH volume + price UP   = institutional ACCUMULATION = BULLISH signal.\n"
    "HIGH volume + price FLAT = contested session = NEUTRAL signal.\n"
    "You are FORBIDDEN from interpreting high volume as 'increased demand from buyers' or "
    "'institutional accumulation' unless the price is also moving UP on that volume.\n"
    "You are FORBIDDEN from using volume as a proxy for commodity demand "
    "(e.g. iron ore demand from China). Volume refers only to share trading activity, "
    "not physical commodity demand.\n"
    "If the Volume label in the context says SELLOFF or DISTRIBUTION — treat it as a BEARISH signal.\n"
    "If the Volume label says ACCUMULATION or RALLY — treat it as a BULLISH signal.\n"
    "If the Volume label says 'DO NOT assume bullish or bearish' — do NOT use volume as a primary signal.\n"
)

_TREND_MOMENTUM_RULE = (
    "TREND MOMENTUM RULE (mandatory — read before analysing any signal):\n"
    "The TREND MOMENTUM block at the top of the market context shows the stock's multi-day price trend.\n"
    "STRONG_DOWNTREND means: 5-day return < -3%, 20-day return < -5%, or 3+ consecutive down sessions.\n"
    "If trend_label = STRONG_DOWNTREND: you need CRITICAL-rated company-specific news to vote bullish. "
    "Without CRITICAL bullish evidence, default to bearish or neutral.\n"
    "If trend_label = DOWNTREND: bullish votes require at least MODERATE-rated supportive evidence.\n"
    "If trend_label = STRONG_UPTREND: you need CRITICAL-rated bearish news to justify a bearish vote.\n"
    "If trend_label = NEUTRAL or UPTREND: use normal signal analysis — no extra bias.\n"
    "Consecutive down sessions count: if 4 or more consecutive sessions closed lower, "
    "treat as structural selling pressure until a confirmed reversal session appears.\n"
)

_AUDUSD_RULE = (
    "AUD/USD INTERPRETATION RULE (mandatory):\n"
    "AUD/USD weakness is NOT automatically bullish for ASX miners.\n"
    "CORRECT logic: AUD/USD fall of >0.5% = risk-off signal = BEARISH for equities in general.\n"
    "WRONG logic: 'AUD weakness boosts USD revenue' — this is only true for exporters with USD-priced "
    "exports AND stable demand, which requires CRITICAL news confirmation.\n"
    "FORBIDDEN: Using AUD/USD decline as a standalone bullish signal without confirming that "
    "(a) the company's revenues are primarily USD-denominated AND "
    "(b) iron ore / commodity volumes are not simultaneously falling.\n"
    "Default: AUD/USD decline > 0.5% = BEARISH (risk-off). "
    "Only override to bullish if CRITICAL FX-revenue news explicitly supports it.\n"
)


def _macro_bull_prompt(ticker: str) -> str:
    return (
        f"You are a bullish macro analyst. Your ONLY job is to find reasons why {ticker} might go UP "
        f"in the next 24 hours. Look for: China stimulus signals, infrastructure demand, supply shortages, "
        f"positive earnings revisions, AUD weakness (which boosts USD-denominated revenue), "
        f"or any bullish technical setup. "
        f"You are FORBIDDEN from mentioning bearish factors.\n\n"
        f"{_TREND_MOMENTUM_RULE}\n"
        f"{_AUDUSD_RULE}\n"
        f"{_NEWS_PRIORITY_RULE}\n"
        f"{_BROAD_MARKET_RULE}\n"
        f"{_VOLUME_RULE}\n"
        f"Return only: VOTE: bullish | REASON: [one sentence]"
    )


def _geo_bear_prompt(ticker: str) -> str:
    return (
        f"You are a bearish geopolitical risk analyst. Your ONLY job is to find reasons why {ticker} might go DOWN "
        f"in the next 24 hours. Look for: conflict escalation, shipping disruptions, sanctions, "
        f"risk-off sentiment in Asian markets, commodity demand destruction, "
        f"or margin compression from rising energy costs. "
        f"You are FORBIDDEN from mentioning bullish factors.\n\n"
        f"{_TREND_MOMENTUM_RULE}\n"
        f"{_AUDUSD_RULE}\n"
        f"{_NEWS_PRIORITY_RULE}\n"
        f"{_BROAD_MARKET_RULE}\n"
        f"{_VOLUME_RULE}\n"
        f"Return only: VOTE: bearish | REASON: [one sentence]"
    )


def _quant_prompt(ticker: str) -> str:
    return (
        f"You are a quantitative technical analyst. You IGNORE all news, geopolitics, and macroeconomics. "
        f"You only analyse price action and technical indicators for {ticker}. "
        f"Based on the provided RSI, MACD signal, volume trend, and 20-day moving average data in the market context, "
        f"determine if the stock is technically overbought, oversold, or neutral.\n\n"
        f"VOLUME RULE (MANDATORY — overrides all other signals):\n"
        f"- If the Volume label in the context contains 'EXTREME' or 'HIGH': "
        f"you are FORBIDDEN from returning VOTE: neutral. "
        f"The market has made a decision. Determine direction from price action and MACD only, then vote directionally.\n"
        f"- If Volume label contains 'ELEVATED': neutral is allowed only if RSI is between 45-55 AND MACD is flat.\n"
        f"- If Volume label contains 'NORMAL' or 'UNAVAILABLE': neutral is always acceptable.\n"
        f"- If RSI is marked UNAVAILABLE: rely entirely on MACD signal and volume for your vote.\n\n"
        f"{_TREND_MOMENTUM_RULE}\n"
        f"{_AUDUSD_RULE}\n"
        f"{_BROAD_MARKET_RULE}\n"
        f"{_VOLUME_RULE}\n"
        f"Return only: VOTE: [bullish/bearish/neutral] | REASON: [one sentence referencing a specific indicator]"
    )


def get_neutral_agent_bias_instruction(trend_label: str) -> str:
    """
    Returns a trend-aware default assumption for neutral fundamentals agents.
    In a downtrend, burden of proof shifts to the bulls — uncertainty = bearish.
    In an uptrend, burden of proof shifts to the bears — uncertainty = bullish.
    """
    if trend_label == "STRONG_DOWNTREND":
        return (
            "IMPORTANT: This stock is in a confirmed STRONG DOWNTREND "
            "(down 8%+ this month, consecutive down days). "
            "In a downtrend, the burden of proof is on the bulls. "
            "If you cannot find a SPECIFIC, MEASURABLE bullish catalyst "
            "(not vague sentiment, not currency moves, not volume), "
            "your default vote must be BEARISH, not neutral. "
            "Uncertainty in a downtrend = bearish."
        )
    elif trend_label == "DOWNTREND":
        return (
            "NOTE: This stock is in a downtrend. "
            "If signals are mixed or unclear, lean bearish rather than neutral. "
            "Require specific evidence to vote bullish."
        )
    elif trend_label == "STRONG_UPTREND":
        return (
            "IMPORTANT: This stock is in a confirmed STRONG UPTREND. "
            "In an uptrend, the burden of proof is on the bears. "
            "If you cannot find a SPECIFIC, MEASURABLE bearish catalyst, "
            "your default vote must be BULLISH, not neutral."
        )
    elif trend_label == "UPTREND":
        return (
            "NOTE: This stock is in an uptrend. "
            "If signals are mixed or unclear, lean bullish rather than neutral."
        )
    else:
        return "Be balanced — consider both upside and downside equally."


def _neutral_fund_prompt(ticker: str, trend_label: str = "NEUTRAL") -> str:
    bias_instruction = get_neutral_agent_bias_instruction(trend_label)
    return (
        f"You are a fundamental analyst focused on {ticker}'s core business. "
        f"Analyse the provided commodity prices, currency rates, and recent company news "
        f"to determine fair value direction over the next 24 hours.\n\n"
        f"{bias_instruction}\n\n"
        f"{_TREND_MOMENTUM_RULE}\n"
        f"{_AUDUSD_RULE}\n"
        f"{_NEWS_PRIORITY_RULE}\n"
        f"{_BROAD_MARKET_RULE}\n"
        f"{_VOLUME_RULE}\n"
        f"Return only: VOTE: [bullish/bearish/neutral] | REASON: [one sentence]"
    )


def _blind_judge_prompt(ticker: str, lessons_block: str) -> str:
    """
    Call 1 of 2-stage Judge pipeline.
    Receives arguments ONLY — no vote counts — to prevent anchoring.
    """
    return (
        f"You are an impartial senior analyst evaluating arguments about {ticker} for the next 24 hours.\n\n"
        f"You do NOT know how many agents voted for each side. Evaluate ONLY the logic and evidence.\n\n"
        f"{lessons_block}\n\n"
        f"EVALUATION CRITERIA:\n"
        f"1. Which side cited SPECIFIC, MEASURABLE data? (exact prices, %, confirmed events, named sources)\n"
        f"2. Which side used VAGUE SENTIMENT or ASSUMPTIONS? (words like 'may', 'could', 'potential')\n"
        f"3. Does the causal chain reasoning actually support the conclusion? "
        f"If cost/revenue/demand/sentiment all point bearish but any argument concludes bullish — "
        f"that is a LOGIC FAILURE. Flag it.\n"
        f"4. Which CRITICAL-rated news items exist and which side do they support? "
        f"CRITICAL signals must dominate the verdict.\n\n"
        f"Return EXACTLY these five lines (no JSON, no markdown):\n"
        f"LOGIC_VERDICT: [bullish/bearish/neutral]\n"
        f"LOGIC_CONFIDENCE: [high/medium/low]\n"
        f"STRONGEST_EVIDENCE: [one sentence — the single most compelling data point from either side]\n"
        f"WEAKEST_ARGUMENT: [one sentence — the most obviously flawed reasoning from either side]\n"
        f"REASONING: [two sentences maximum explaining your verdict]\n"
    )


def _reconciler_prompt(
    ticker: str,
    logic_verdict: str,
    logic_confidence: str,
    n_bull: int,
    n_bear: int,
    n_neut: int,
    market_session: str,
    top_critical_news: str,
    axjo_change_pct: Optional[float],
    spx_change_pct: Optional[float],
    lessons_block: str,
) -> str:
    """
    Call 2 of 2-stage Judge pipeline.
    Reconciles Blind Judge verdict with vote tally, applies market session rules,
    and generates the full structured causal chain output.
    """
    axjo_str = f"{axjo_change_pct:+.2f}%" if axjo_change_pct is not None else "N/A"
    spx_str  = f"{spx_change_pct:+.2f}%"  if spx_change_pct  is not None else "N/A"

    vote_majority = "bullish" if n_bull > n_bear else ("bearish" if n_bear > n_bull else "neutral")

    return (
        f"You are the final reconciler for a {ticker} market prediction.\n\n"
        f"=== BLIND LOGIC JUDGE VERDICT ===\n"
        f"Logic Verdict: {logic_verdict}\n"
        f"Logic Confidence: {logic_confidence}\n"
        f"=== END BLIND VERDICT ===\n\n"
        f"=== VOTE TALLY ===\n"
        f"Agent votes: {n_bull} bullish | {n_bear} bearish | {n_neut} neutral\n"
        f"Vote majority: {vote_majority}\n"
        f"=== END TALLY ===\n\n"
        f"=== MARKET CONTEXT ===\n"
        f"Market Session: {market_session}\n"
        f"Top News Signal: {top_critical_news}\n"
        f"Broad Market: ASX {axjo_str} | SPX {spx_str}\n"
        f"=== END MARKET CONTEXT ===\n\n"
        f"{lessons_block}\n\n"
        f"RECONCILIATION RULES (apply strictly in order):\n\n"
        f"RULE 1 — Agreement:\n"
        f"  If logic_verdict == vote_majority → FINAL: logic_verdict, confidence_modifier = +5\n\n"
        f"RULE 2 — Disagreement, high logic confidence:\n"
        f"  If logic_verdict != vote_majority AND logic_confidence = high:\n"
        f'  → FINAL: logic_verdict (overrides votes), confidence_modifier = -10, override_flag = "LOGIC_OVERRIDE"\n\n'
        f"RULE 3 — Disagreement, medium logic confidence:\n"
        f"  If logic_verdict != vote_majority AND logic_confidence = medium:\n"
        f'  → FINAL: logic_verdict, confidence_modifier = -15, override_flag = "LOGIC_OVERRIDE_WEAK"\n\n'
        f"RULE 4 — Disagreement, low logic confidence:\n"
        f"  If logic_verdict != vote_majority AND logic_confidence = low:\n"
        f'  → FINAL: vote_majority (trust votes when logic is weak), confidence_modifier = -10, override_flag = "VOTES_HELD_LOW_LOGIC"\n\n'
        f"RULE 5 — Market session override:\n"
        f"  If market_session = BROAD_SELLOFF AND final direction = bullish:\n"
        f"  Unless logic_confidence = high: downgrade to neutral, add confidence_modifier = -10, "
        f'override_flag = "SELLOFF_DOWNGRADE"\n\n'
        f"Return ONLY valid JSON (no markdown). String values must be FULL SENTENCES of 8-20 words:\n"
        f'{{"verdict": "bullish|bearish|neutral", '
        f'"confidence_modifier": 10 or 0 or -10, '
        f'"override_flag": "string or null", '
        f'"reasoning": "Two sentences explaining the reconciled conclusion.", '
        f'"trigger_event": "Specific event name, approximate date, and source/context.", '
        f'"cost_impact": "Full sentence: how this event affects {ticker} input costs — state direction with reasoning.", '
        f'"revenue_impact": "Full sentence: how this event affects {ticker} commodity revenue — state direction with reasoning.", '
        f'"demand_signal": "Full sentence: what this means for {ticker} buyers such as Chinese steel mills — state direction with reasoning.", '
        f'"sentiment_signal": "Full sentence: risk-on or risk-off? What do AUD/USD or iron ore futures signal — state direction with reasoning."}}'
    )


# ── Bug Fix 2: Trigger event validation ───────────────────────────────────────

def validate_trigger_event(trigger_event: str, ticker: str, news_items: list) -> str:
    """
    Ensures agents always receive a trigger event context.
    Falls back through 3 levels before giving up.
    """
    # Level 1: Use existing trigger if valid
    if trigger_event and trigger_event.strip() and "No data" not in trigger_event:
        return trigger_event

    # Level 2: Build trigger from raw news items (last 24h only)
    if news_items:
        recent = [n for n in news_items if n.get("hours_old", 999) <= 24]
        if recent:
            top = sorted(recent, key=lambda x: x.get("weight", 0), reverse=True)[0]
            headline = top.get("title", top.get("headline", "Market event"))
            source   = top.get("source", "MarketAux")
            return f"{headline} (Source: {source}, {top.get('hours_old', '?')}h ago)"

    # Level 3: No news — macro/technical-driven session
    return f"No major catalyst identified for {ticker} in last 24h — likely macro/technical-driven session"


# ── Bug Fix 4: Smart direction determination ───────────────────────────────────

def determine_direction(
    bullish: int,
    bearish: int,
    neutral: int,
    volume_vs_avg: Optional[float],
    trigger_event: str,
    confidence: float,
) -> str:
    """
    Determines final direction with commodity-stock bias correction.
    Pure neutral is only returned when conditions genuinely support it.
    Returns 'bullish' | 'bearish' | 'neutral'.
    """
    total        = bullish + bearish + neutral
    neutral_ratio = neutral / total if total > 0 else 0
    no_catalyst  = trigger_event.startswith("No major catalyst")

    # Clear majority (margin >= 5)
    if bullish > bearish and (bullish - bearish) >= 5:
        return "bullish"
    if bearish > bullish and (bearish - bullish) >= 5:
        return "bearish"

    # Near-split on high-volume day with no clear winner = institutional distribution → bearish
    if volume_vs_avg is not None and volume_vs_avg >= 2.0 and neutral_ratio > 0.4:
        return "bearish"

    # Genuine neutral: no catalyst + low volume
    if no_catalyst and (volume_vs_avg is None or volume_vs_avg < 1.3):
        return "neutral"

    # Tiebreaker: asymmetric commodity risk — commodities fall faster than they rise
    if bullish == bearish:
        return "bearish"

    return "bullish" if bullish > bearish else "bearish"


# ── Fix 1: Minimum confidence guard ────────────────────────────────────────────

def apply_minimum_confidence_guard(
    direction: str,
    confidence: float,
    bullish: int,
    bearish: int,
    neutral: int,
) -> Tuple[str, float, Optional[str]]:
    """
    Prevents directional predictions when confidence is too low to be meaningful.
    confidence must be in 0–100 percentage scale.
    direction must be 'bullish' | 'bearish' | 'neutral'.
    Returns (direction, confidence, signal_note_or_None).
    """
    total         = bullish + bearish + neutral
    neutral_ratio = neutral / total if total > 0 else 1.0

    # Rule 1: Hard zero confidence — no direction possible
    if confidence < 3.0:
        return (
            "neutral",
            confidence,
            "INSUFFICIENT_SIGNAL: confidence below minimum threshold — "
            "no directional prediction generated",
        )

    # Rule 2: Majority neutral — market direction genuinely unclear
    if neutral_ratio >= 0.50:
        return (
            "neutral",
            confidence,
            "INSUFFICIENT_SIGNAL: majority of agents returned neutral — "
            "market direction unclear",
        )

    # Rule 3: Near-tie at low confidence — margin too thin to call
    margin = abs(bullish - bearish)
    if margin <= 2 and confidence < 15.0:
        return (
            "neutral",
            confidence,
            f"INSUFFICIENT_SIGNAL: agent margin too thin ({margin} agents) "
            f"at low confidence ({confidence:.1f}%) — defaulting to neutral",
        )

    return direction, confidence, None


# ── Fix 2: Causal chain audit ───────────────────────────────────────────────────

_BEARISH_KEYWORDS = frozenset([
    # Unambiguously negative — count in all trend contexts
    "negative", "decrease", "decline", "drop", "risk", "disruption", "lower",
    "weigh", "sell-off", "selloff", "compressed", "hurt", "pressure", "headwind",
    "contraction", "slowdown", "ban", "sanction", "tariff", "loss", "deficit",
    "shortage", "bearish", "downward", "fall", "weak", "cut", "down",
])

# Uncertainty/vagueness words: the bull case has NOT been proven.
# Count as BEARISH only in downtrends, BULLISH only in uptrends, NEUTRAL otherwise.
_UNCERTAINTY_KEYWORDS = frozenset([
    "unclear", "uncertain", "mixed", "difficult", "limited", "remains",
    "potential", "may", "could", "might", "possible", "suggests", "perhaps",
    "visibility", "ambiguous", "inconclusive",
])

_BULLISH_KEYWORDS = frozenset([
    # Measurable bullish signals only — no vague positives
    "increase", "positive", "rise", "boost", "gain", "higher", "benefit",
    "growth", "accumulation", "strong", "demand", "recovery", "stimulus",
    "upgrade", "expansion", "bullish", "upward", "rally", "surge",
    "outperform", "improve", "rebound", "support", "tailwind", "opportunity", "up",
])

_DOWNTREND_LABELS = frozenset(["STRONG_DOWNTREND", "DOWNTREND"])
_UPTREND_LABELS   = frozenset(["STRONG_UPTREND", "UPTREND"])


def audit_causal_chain(
    judge_result: Dict[str, Any],
    trend_label: str = "NEUTRAL",
) -> Tuple[str, int, int, Dict[str, str]]:
    """
    Counts bearish vs bullish signals in the 4 causal chain slots.
    If ≥3 of 4 slots point the same direction, that direction is the chain verdict.

    Trend-aware behaviour:
      - Empty slots: in a downtrend count as bearish (bull case unproven), else neutral
      - Tied scores:  in a downtrend count as bearish, in an uptrend as bullish, else neutral
      - Uncertainty words ("unclear", "may", "suggests"…) in bearish keyword list — in a
        downtrend they count against the bull case

    Returns (chain_verdict, bearish_slot_count, bullish_slot_count, slot_verdicts_dict).
    """
    is_downtrend = trend_label in _DOWNTREND_LABELS
    is_uptrend   = trend_label in _UPTREND_LABELS

    slots = {
        "cost":      judge_result.get("cost_impact", ""),
        "revenue":   judge_result.get("revenue_impact", ""),
        "demand":    judge_result.get("demand_signal", ""),
        "sentiment": judge_result.get("sentiment_signal", ""),
    }

    bearish_slots = 0
    bullish_slots = 0
    slot_verdicts: Dict[str, str] = {}

    for slot_name, slot_text in slots.items():
        if not slot_text or len(slot_text.strip()) < 10 or "No data" in slot_text:
            # Empty slot — in downtrend counts as bearish (bull case unproven)
            if is_downtrend:
                bearish_slots += 1
                slot_verdicts[slot_name] = "bearish (empty=downtrend default)"
            elif is_uptrend:
                bullish_slots += 1
                slot_verdicts[slot_name] = "bullish (empty=uptrend default)"
            else:
                slot_verdicts[slot_name] = "neutral (empty)"
            continue

        # Word-level tokenisation — prevents "up" hitting inside "disruptions" etc.
        words = [w.rstrip(".,;:!?") for w in slot_text.lower().split()]
        b_hits   = sum(1 for w in words if w in _BEARISH_KEYWORDS)
        u_hits   = sum(1 for w in words if w in _BULLISH_KEYWORDS)
        unc_hits = sum(1 for w in words if w in _UNCERTAINTY_KEYWORDS)

        # Uncertainty keywords: only shift the score in trending markets.
        # An unproven bull case in a downtrend counts as bearish; vice-versa in uptrend.
        if unc_hits > 0:
            if is_downtrend:
                b_hits += unc_hits
            elif is_uptrend:
                u_hits += unc_hits
            # NEUTRAL: uncertainty is ignored — neither side gets credit

        if b_hits > u_hits:
            bearish_slots += 1
            slot_verdicts[slot_name] = f"bearish (b={b_hits}, u={u_hits})"
        elif u_hits > b_hits:
            bullish_slots += 1
            slot_verdicts[slot_name] = f"bullish (b={b_hits}, u={u_hits})"
        else:
            # Tie — default direction based on trend
            if is_downtrend:
                bearish_slots += 1
                slot_verdicts[slot_name] = f"bearish (tie={b_hits}=downtrend default)"
            elif is_uptrend:
                bullish_slots += 1
                slot_verdicts[slot_name] = f"bullish (tie={u_hits}=uptrend default)"
            else:
                slot_verdicts[slot_name] = f"neutral (tied b={b_hits} u={u_hits})"

    if bearish_slots >= 3:
        chain_verdict = "bearish"
    elif bullish_slots >= 3:
        chain_verdict = "bullish"
    else:
        chain_verdict = "neutral"

    return chain_verdict, bearish_slots, bullish_slots, slot_verdicts


def get_persona_distribution(trend_label: str) -> dict:
    """
    Adjusts agent persona counts based on market trend to counteract LLM optimistic bias.

    In a downtrend: more bear agents, fewer neutral (who default bullish when uncertain).
    In an uptrend: more bull agents, fewer neutral.
    Total always = 45 agents.

    Returns a dict with counts + description for API transparency.
    """
    distributions = {
        "STRONG_DOWNTREND": {
            "macro_bull": 5, "geo_bear": 18, "quant": 10, "neutral_fund": 12,
            "description": "Bear-weighted: strong downtrend confirmed",
        },
        "DOWNTREND": {
            "macro_bull": 8, "geo_bear": 14, "quant": 10, "neutral_fund": 13,
            "description": "Mild bear-weighted: downtrend in progress",
        },
        "NEUTRAL": {
            "macro_bull": 10, "geo_bear": 10, "quant": 10, "neutral_fund": 15,
            "description": "Balanced: no clear trend",
        },
        "SIDEWAYS": {
            "macro_bull": 10, "geo_bear": 10, "quant": 10, "neutral_fund": 15,
            "description": "Balanced: no clear trend",
        },
        "UPTREND": {
            "macro_bull": 14, "geo_bear": 8, "quant": 10, "neutral_fund": 13,
            "description": "Mild bull-weighted: uptrend in progress",
        },
        "STRONG_UPTREND": {
            "macro_bull": 18, "geo_bear": 5, "quant": 10, "neutral_fund": 12,
            "description": "Bull-weighted: strong uptrend confirmed",
        },
        "UNKNOWN": {
            "macro_bull": 10, "geo_bear": 10, "quant": 10, "neutral_fund": 15,
            "description": "Balanced: trend unknown",
        },
    }
    dist = distributions.get(trend_label, distributions["UNKNOWN"])
    total = dist["macro_bull"] + dist["geo_bear"] + dist["quant"] + dist["neutral_fund"]
    assert total == 45, f"Persona distribution for {trend_label} sums to {total}, expected 45"
    return dist


# Default balanced persona distribution (used for __init__ placeholder)
PERSONA_DISTRIBUTION = [
    ("macro_bull",   10, _macro_bull_prompt),
    ("geo_bear",     10, _geo_bear_prompt),
    ("quant",        10, _quant_prompt),
    ("neutral_fund", 15, _neutral_fund_prompt),
]


# ═══════════════════════════════════════════════════════════════════════════════
# Agent class
# ═══════════════════════════════════════════════════════════════════════════════

class AdversarialAgent:
    """Single adversarial agent with a locked persona."""

    def __init__(self, agent_id: int, persona: str, system_prompt: str):
        self.agent_id    = agent_id
        self.persona     = persona
        self.system_prompt = system_prompt

    async def vote(
        self,
        llm_router: LLMRouter,
        event_context: str,
        market_context_block: str,
    ) -> Dict[str, Any]:
        """Return a vote dict: {agent_id, persona, vote, reason}."""

        user_prompt = (
            f"{market_context_block}\n\n"
            f"=== GEOPOLITICAL EVENT ===\n{event_context}\n=== END EVENT ===\n\n"
            f"Now give your vote and one-sentence reason as instructed."
        )

        try:
            response = await llm_router.call_boost(
                system_message=self.system_prompt,
                user_prompt=user_prompt,
                session_id=f"agent_{self.agent_id}_{self.persona}",
            )
            vote, reason = _parse_vote(response, self.persona)
        except Exception as e:
            logger.warning("Agent %d (%s) error: %s", self.agent_id, self.persona, e)
            vote   = "neutral"
            reason = "Error — defaulting to neutral"

        return {"agent_id": self.agent_id, "persona": self.persona, "vote": vote, "reason": reason}


def _parse_vote(response: str, persona: str) -> Tuple[str, str]:
    """Extract vote and reason from agent response."""
    # Macro bull can only be bullish; geo bear can only be bearish
    if persona == "macro_bull":
        forced_vote = "bullish"
    elif persona == "geo_bear":
        forced_vote = "bearish"
    else:
        forced_vote = None

    lower = response.lower()

    # Parse VOTE: field
    vote = None
    if "vote:" in lower:
        after = lower.split("vote:", 1)[1].strip()
        for candidate in ("bullish", "bearish", "neutral"):
            if after.startswith(candidate):
                vote = candidate
                break
        if vote is None:
            for candidate in ("bullish", "bearish", "neutral"):
                if candidate in after[:30]:
                    vote = candidate
                    break

    if forced_vote:
        vote = forced_vote
    elif vote is None:
        if "bullish" in lower[:100] or "up" in lower[:60]:
            vote = "bullish"
        elif "bearish" in lower[:100] or "down" in lower[:60]:
            vote = "bearish"
        else:
            vote = "neutral"

    # Parse REASON: field
    reason = ""
    if "reason:" in lower:
        parts = response.split(":", 1)
        if len(parts) > 1:
            # find the REASON: part
            idx = response.upper().find("REASON:")
            if idx != -1:
                reason = response[idx + 7:].strip().split("\n")[0].strip()[:300]
    if not reason:
        reason = response.strip()[:200]

    return vote, reason


# ═══════════════════════════════════════════════════════════════════════════════
# Simulation class — full upgraded pipeline
# ═══════════════════════════════════════════════════════════════════════════════

class Simulation:
    """Adversarial 45-agent simulation with Judge, programmatic confidence, and live data."""

    def __init__(self, llm_router: LLMRouter):
        self.llm_router    = llm_router
        self.simulation_id = f"sim_{datetime.now().strftime('%Y%m%d_%H%M%S')}_{uuid.uuid4().hex[:6]}"
        self.agents: List[AdversarialAgent] = []
        self._persona_config = list(PERSONA_DISTRIBUTION)  # default; overridden per trend
        self._init_agents()

    def _init_agents(self):
        self.agents = []
        agent_id = 1
        for persona, count, _ in self._persona_config:
            for _ in range(count):
                self.agents.append(AdversarialAgent(agent_id, persona, ""))
                agent_id += 1
        logger.info("Initialized %d adversarial agents", len(self.agents))

    def _reinit_agents_for_trend(self, trend_label: str) -> str:
        """
        Rebuild the agent pool using a trend-weighted persona distribution.
        Returns the description string for logging + API response.
        """
        dist = get_persona_distribution(trend_label)
        self._persona_config = [
            ("macro_bull",   dist["macro_bull"],   _macro_bull_prompt),
            ("geo_bear",     dist["geo_bear"],      _geo_bear_prompt),
            ("quant",        dist["quant"],         _quant_prompt),
            ("neutral_fund", dist["neutral_fund"],  _neutral_fund_prompt),
        ]
        self._init_agents()
        logger.info(
            "[PERSONA] %s → bull=%d bear=%d quant=%d neutral=%d | %s",
            trend_label, dist["macro_bull"], dist["geo_bear"],
            dist["quant"], dist["neutral_fund"], dist["description"],
        )
        return dist["description"]

    def _set_agent_prompts(self, ticker: str, lessons_str: str, trend_label: str = "NEUTRAL"):
        """Set per-persona system prompts with the actual ticker and trend-aware bias."""
        idx = 0
        for persona, count, prompt_fn in self._persona_config:
            if persona == "neutral_fund":
                # Inject trend-aware burden-of-proof bias at runtime
                prompt = _neutral_fund_prompt(ticker, trend_label)
            else:
                prompt = prompt_fn(ticker)
            for _ in range(count):
                self.agents[idx].system_prompt = prompt
                idx += 1

    async def run_simulation(
        self, event_data: dict, ticker: str, num_rounds: int = 1
    ) -> Dict[str, Any]:
        """
        Full upgraded pipeline — runs in exactly this order:
          1. fetch_market_context
          2. set agent prompts with ticker + lessons
          3. run 45 agents in parallel
          4. tally votes
          5. calculate_confidence()
          6. run Judge
          7. apply confidence_modifier
          8. return results dict
        """
        logger.info("=== SIMULATION %s START (ticker=%s) ===", self.simulation_id, ticker)

        # ── STEP 1: Fetch live market context + lessons ────────────────────────
        from services.market_context import fetch_market_context
        market_ctx = await fetch_market_context(ticker)
        logger.info("Market context fetched: iron_ore=%.2f audusd=%.4f brent=%.2f rsi=%s quality=%s",
                    market_ctx["iron_ore_price"], market_ctx["audusd_rate"],
                    market_ctx["brent_price"],
                    market_ctx.get("ticker_rsi") or "UNAVAILABLE",
                    market_ctx.get("data_quality", "?"))

        lessons     = market_ctx.get("lessons", [])
        lessons_str = "\n".join(f"- {l}" for l in lessons) if lessons else "No past lessons available."
        context_block = market_ctx["context_block"]

        # ── STEP 1b: Rebalance personas based on trend ────────────────────────
        trend_label = market_ctx.get("trend_label", "NEUTRAL") or "NEUTRAL"
        persona_distribution_desc = self._reinit_agents_for_trend(trend_label)

        # ── STEP 2: Set agent prompts (with trend-aware neutral bias) ─────────
        self._set_agent_prompts(ticker, lessons_str, trend_label)

        # ── STEP 3: Build event context string ────────────────────────────────
        event_context = (
            f"Country: {event_data.get('country', 'Unknown')}\n"
            f"Event Type: {event_data.get('event_type', 'Unknown')}\n"
            f"Fatalities: {event_data.get('fatalities', 0)}\n"
            f"Date: {event_data.get('event_date', 'Unknown')}\n"
            f"Description: {event_data.get('notes', event_data.get('location', 'No description'))}"
        )

        # ── STEP 4: Run 45 agents in parallel ─────────────────────────────────
        logger.info("Running %d adversarial agents in parallel ...", len(self.agents))
        all_votes = await asyncio.gather(*[
            agent.vote(self.llm_router, event_context, context_block)
            for agent in self.agents
        ])

        # ── STEP 5: Tally votes ───────────────────────────────────────────────
        bullish_votes = [v for v in all_votes if v["vote"] == "bullish"]
        bearish_votes = [v for v in all_votes if v["vote"] == "bearish"]
        neutral_votes = [v for v in all_votes if v["vote"] == "neutral"]

        n_bull = len(bullish_votes)
        n_bear = len(bearish_votes)
        n_neut = len(neutral_votes)

        logger.info("Vote tally: bullish=%d bearish=%d neutral=%d", n_bull, n_bear, n_neut)

        # ── STEP 6: Calculate confidence programmatically ─────────────────────
        raw_confidence = calculate_confidence(n_bull, n_bear, n_neut)
        logger.info("Programmatic confidence: %.1f%% (method: weighted_variance_v2)", raw_confidence * 100)

        # ── STEP 7: Run Judge agent (sequential, after all others) ───────────
        news_items    = market_ctx.get("news_items", [])
        market_session = market_ctx.get("market_session", "UNKNOWN")
        axjo_change_pct = market_ctx.get("axjo_change_pct")
        spx_change_pct  = market_ctx.get("spx_change_pct")

        # Extract top CRITICAL news headline for Judge context
        critical_items = [n for n in news_items if n.get("weight", 0) >= 0.85]
        if critical_items:
            top_item = sorted(critical_items, key=lambda x: x.get("weight", 0), reverse=True)[0]
            top_critical_news = top_item.get("title", top_item.get("headline", "Unknown"))
        else:
            top_critical_news = "None"

        judge_result = await self._run_judge(
            ticker, n_bull, n_bear, n_neut,
            bullish_votes[:3], bearish_votes[:3],
            [v for v in all_votes if v["persona"] == "quant"][:3],
            [v for v in all_votes if v["persona"] == "neutral_fund"][:3],
            context_block, lessons_str, event_context,
            has_news=bool(news_items),
            market_session=market_session,
            top_critical_news=top_critical_news,
            axjo_change_pct=axjo_change_pct,
            spx_change_pct=spx_change_pct,
        )

        # ── STEP 8: Validate trigger_event + apply confidence modifier ─────────
        raw_trigger   = judge_result.get("trigger_event", "")
        trigger_event = validate_trigger_event(raw_trigger, ticker, news_items)
        judge_result["trigger_event"] = trigger_event

        modifier = judge_result.get("confidence_modifier", 0)
        final_confidence = max(0.0, min(1.0, raw_confidence + modifier / 100))

        # Bug Fix 5: reduce confidence when data quality is poor
        if market_ctx.get("data_quality") == "POOR":
            final_confidence = max(0.0, final_confidence - 0.20)
            logger.warning("Data quality POOR — confidence reduced by 20%%")

        logger.info("Judge verdict: %s | modifier: %+d | final confidence: %.1f%%",
                    judge_result.get("verdict", "?"), modifier, final_confidence * 100)

        # ── Bug Fix 4: Smart direction determination (after judge, with trigger) ─
        volume_vs_avg = market_ctx.get("ticker_volume_vs_avg")
        raw_dir   = determine_direction(n_bull, n_bear, n_neut, volume_vs_avg, trigger_event, final_confidence)
        direction = {"bullish": "UP", "bearish": "DOWN", "neutral": "NEUTRAL"}[raw_dir]
        logger.info("Direction (smart): %s (volume=%.2fx trigger=%s...)",
                    direction, volume_vs_avg or 0, trigger_event[:40])

        # ── Fix 2: Causal chain audit — logic must match conclusion ──────────────
        chain_verdict, chain_bearish, chain_bullish, slot_verdicts = audit_causal_chain(
            judge_result, trend_label=trend_label
        )
        chain_override_flag: Optional[str] = None

        direction_raw = {"UP": "bullish", "DOWN": "bearish", "NEUTRAL": "neutral"}[direction]
        if chain_verdict != "neutral" and chain_verdict != direction_raw:
            original_direction = direction
            direction    = {"bullish": "UP", "bearish": "DOWN"}[chain_verdict]
            direction_raw = chain_verdict
            final_confidence = max(0.0, round(final_confidence * 0.85, 3))
            chain_override_flag = (
                f"CHAIN_OVERRIDE: causal analysis ({chain_bearish} bearish slots, "
                f"{chain_bullish} bullish slots) contradicted agent majority "
                f"({original_direction}) — logic applied, direction changed to {direction}"
            )
            logger.info("Chain audit OVERRIDE: %s → %s (%.1f%% confidence)",
                        original_direction, direction, final_confidence * 100)
        elif chain_verdict != "neutral" and chain_verdict == direction_raw:
            final_confidence = min(round(final_confidence * 1.15, 3), 0.95)
            chain_override_flag = (
                f"CHAIN_CONFIRMED: causal analysis agrees with agent majority "
                f"({chain_bearish} bearish, {chain_bullish} bullish slots)"
            )
            logger.info("Chain audit CONFIRMED: %s (%.1f%% confidence)", direction, final_confidence * 100)

        # ── Fix 2 (cont.): Apply broad market session modifier ────────────────
        from services.market_context import apply_market_session_modifier
        judge_verdict_str = judge_result.get("verdict", "neutral")
        final_confidence, market_warning = apply_market_session_modifier(
            confidence=final_confidence,
            direction=judge_verdict_str,
            market_session=market_session,
        )
        if market_warning:
            logger.info("Market session modifier applied: %s", market_warning)

        # ── Fix 1: Minimum confidence guard ──────────────────────────────────
        confidence_pct = round(final_confidence * 100, 3)
        direction_raw, confidence_pct, signal_note = apply_minimum_confidence_guard(
            direction=direction_raw,
            confidence=confidence_pct,
            bullish=n_bull,
            bearish=n_bear,
            neutral=n_neut,
        )
        direction       = {"bullish": "UP", "bearish": "DOWN", "neutral": "NEUTRAL"}[direction_raw]
        final_confidence = round(confidence_pct / 100, 5)
        if signal_note:
            logger.info("Confidence guard triggered: %s", signal_note)

        return {
            "simulation_id":    self.simulation_id,
            "ticker":           ticker,
            "event_data":       event_data,
            "direction":        direction,
            "raw_confidence":   raw_confidence,
            "final_confidence": final_confidence,
            "n_bull": n_bull, "n_bear": n_bear, "n_neut": n_neut,
            "all_votes":       list(all_votes),
            "judge_result":    judge_result,
            "market_ctx":      market_ctx,
            "lessons":         lessons,
            # Legacy shape for backward compat
            "round_results": [{
                "round": 1,
                "consensus": {"up": n_bull, "down": n_bear, "neutral": n_neut},
                "top_up_rationales":   [v["reason"] for v in bullish_votes[:3]],
                "top_down_rationales": [v["reason"] for v in bearish_votes[:3]],
            }],
            "final_consensus": {"up": n_bull, "down": n_bear, "neutral": n_neut},
            "market_warning":   market_warning,
            "market_session":   market_session,
            # Fix 1
            "signal_note":      signal_note,
            # Fix 2
            "chain_override_flag": chain_override_flag,
            "slot_verdicts":       slot_verdicts,
            # Fix 4 — blind judge fields
            "blind_judge_verdict":    judge_result.get("blind_judge_verdict"),
            "blind_judge_confidence": judge_result.get("blind_judge_confidence"),
            "blind_judge_reasoning":  judge_result.get("blind_judge_reasoning"),
            "reconciler_flag":        judge_result.get("override_flag"),
            "reconciler_reasoning":   judge_result.get("reconciler_reasoning"),
            # Anti-bias: trend-weighted persona distribution used this run
            "persona_distribution":   persona_distribution_desc,
        }

    async def _run_judge(
        self,
        ticker: str,
        n_bull: int, n_bear: int, n_neut: int,
        sample_bull: list, sample_bear: list,
        sample_quant: list, sample_fund: list,
        context_block: str,
        lessons_str: str,
        event_context: str,
        has_news: bool = True,
        market_session: str = "UNKNOWN",
        top_critical_news: str = "None",
        axjo_change_pct: Optional[float] = None,
        spx_change_pct: Optional[float] = None,
    ) -> Dict[str, Any]:
        """
        Two-stage Judge pipeline — prevents vote-count anchoring.

        Call 1 (Blind Judge): sees arguments only, NO vote tally.
        Call 2 (Reconciler):  sees Blind verdict + vote tally → final JSON.
        """

        def _fmt_reasons(votes: list) -> str:
            return "\n".join(f"  - {v['reason']}" for v in votes) if votes else "  (none)"

        lessons_block = f"=== LESSONS FROM PAST PREDICTIONS ===\n{lessons_str}\n=== END LESSONS ==="

        no_catalyst_note = ""
        if not has_news:
            no_catalyst_note = (
                "\n=== NOTE: NO NEWS CATALYST DETECTED ===\n"
                "This is a macro or technical-driven session. "
                "Weight the Quant signals and broad market direction more heavily than geopolitical signals.\n"
                "=== END NOTE ===\n"
            )

        # ── Call 1: Blind Judge — arguments only, no vote tally ───────────────
        blind_user = (
            f"{context_block}\n"
            f"{no_catalyst_note}\n"
            f"=== GEOPOLITICAL EVENT ===\n{event_context}\n=== END EVENT ===\n\n"
            f"=== ARGUMENT SUMMARIES (evaluate logic, not vote counts) ===\n\n"
            f"BULL ARGUMENTS:\n{_fmt_reasons(sample_bull)}\n\n"
            f"BEAR ARGUMENTS:\n{_fmt_reasons(sample_bear)}\n\n"
            f"QUANT SIGNALS:\n{_fmt_reasons(sample_quant)}\n\n"
            f"FUNDAMENTAL ANALYSTS:\n{_fmt_reasons(sample_fund)}\n"
            f"=== END ARGUMENTS ===\n\n"
            f"Evaluate argument quality only. Return three lines as instructed."
        )

        blind_system = _blind_judge_prompt(ticker, lessons_block)

        logic_verdict       = "neutral"
        logic_confidence    = "low"
        blind_reasoning     = "Blind Judge unavailable."
        strongest_evidence  = ""
        weakest_argument    = ""

        try:
            blind_resp = await self.llm_router.call_primary(
                system_message=blind_system,
                user_prompt=blind_user,
                session_id=f"{self.simulation_id}_blind_judge",
            )
            for line in blind_resp.splitlines():
                line_u = line.strip().upper()
                if line_u.startswith("LOGIC_VERDICT:"):
                    val = line.split(":", 1)[1].strip().lower()
                    if val in ("bullish", "bearish", "neutral"):
                        logic_verdict = val
                elif line_u.startswith("LOGIC_CONFIDENCE:"):
                    val = line.split(":", 1)[1].strip().lower()
                    if val in ("high", "medium", "low"):
                        logic_confidence = val
                elif line_u.startswith("STRONGEST_EVIDENCE:"):
                    strongest_evidence = line.split(":", 1)[1].strip()[:400]
                elif line_u.startswith("WEAKEST_ARGUMENT:"):
                    weakest_argument = line.split(":", 1)[1].strip()[:400]
                elif line_u.startswith("REASONING:"):
                    blind_reasoning = line.split(":", 1)[1].strip()[:400]
            logger.info("Blind Judge: verdict=%s confidence=%s", logic_verdict, logic_confidence)
        except Exception as e:
            logger.warning("Blind Judge call failed: %s — using neutral fallback", e)

        # ── Call 2: Reconciler — verdict + vote tally → full causal chain JSON ─
        reconciler_system = _reconciler_prompt(
            ticker=ticker,
            logic_verdict=logic_verdict,
            logic_confidence=logic_confidence,
            n_bull=n_bull,
            n_bear=n_bear,
            n_neut=n_neut,
            market_session=market_session,
            top_critical_news=top_critical_news,
            axjo_change_pct=axjo_change_pct,
            spx_change_pct=spx_change_pct,
            lessons_block=lessons_block,
        )

        reconciler_user = (
            f"{context_block}\n\n"
            f"=== GEOPOLITICAL EVENT ===\n{event_context}\n=== END EVENT ===\n\n"
            f"Blind Judge reasoning summary: {blind_reasoning}\n\n"
            f"Apply reconciliation rules and return JSON verdict."
        )

        defaults = {
            "verdict":             logic_verdict,
            "confidence_modifier": 0,
            "override_flag":       None,
            "reasoning":           blind_reasoning or "Judge unavailable — using raw vote consensus.",
            "trigger_event":       "No data — assumed neutral impact",
            "cost_impact":         "No data — assumed neutral impact",
            "revenue_impact":      "No data — assumed neutral impact",
            "demand_signal":       "No data — assumed neutral impact",
            "sentiment_signal":    "No data — assumed neutral impact",
        }

        try:
            rec_resp = await self.llm_router.call_primary(
                system_message=reconciler_system,
                user_prompt=reconciler_user,
                session_id=f"{self.simulation_id}_reconciler",
            )
            parsed = parse_json_response(rec_resp)
            # Clamp confidence_modifier to +10 / 0 / -10
            mod = int(parsed.get("confidence_modifier", 0))
            parsed["confidence_modifier"] = 10 if mod > 5 else (-10 if mod < -5 else 0)
            for k, v in defaults.items():
                if k not in parsed:
                    parsed[k] = v
            # Attach blind judge fields for downstream use
            parsed["blind_judge_verdict"]    = logic_verdict
            parsed["blind_judge_confidence"] = logic_confidence
            parsed["blind_judge_reasoning"]  = blind_reasoning
            parsed["strongest_evidence"]     = strongest_evidence
            parsed["weakest_argument"]       = weakest_argument
            logger.info(
                "Reconciler: verdict=%s modifier=%+d override=%s",
                parsed.get("verdict"), parsed.get("confidence_modifier"), parsed.get("override_flag"),
            )
            return parsed
        except Exception as e:
            logger.warning("Reconciler call failed: %s — using Blind Judge defaults", e)
            defaults["blind_judge_verdict"]    = logic_verdict
            defaults["blind_judge_confidence"] = logic_confidence
            defaults["blind_judge_reasoning"]  = blind_reasoning
            defaults["strongest_evidence"]     = strongest_evidence
            defaults["weakest_argument"]       = weakest_argument
            return defaults

    async def generate_prediction_report(self, simulation_results: Dict[str, Any]) -> PredictionCard:
        """
        Convert simulation_results into a validated PredictionCard.

        Confidence is taken from programmatic calculation — NOT from LLM.
        Causal chain comes from Judge — NOT from generic LLM.
        """
        ticker       = simulation_results["ticker"]
        ticker_info  = get_ticker_info(ticker)
        event_data   = simulation_results["event_data"]
        judge        = simulation_results["judge_result"]
        market_ctx   = simulation_results["market_ctx"]
        n_bull       = simulation_results["n_bull"]
        n_bear       = simulation_results["n_bear"]
        n_neut       = simulation_results["n_neut"]
        direction    = simulation_results["direction"]
        confidence   = simulation_results["final_confidence"]
        context_block = market_ctx["context_block"]

        logger.info("Generating prediction report for %s (confidence=%.1f%%)", ticker, confidence * 100)

        # ── Build structured causal chain from Judge fields ────────────────────
        causal_chain = _build_causal_chain(judge, direction)

        # ── Build key signals from live market data + votes ───────────────────
        key_signals = _build_key_signals(market_ctx, n_bull, n_bear, n_neut, direction)

        # ── Contrarian and risk factors via LLM (cheap single call) ──────────
        contrarian_view, risk_factors = await self._gen_contrarian_and_risks(
            ticker, ticker_info, event_data, direction, n_bull, n_bear, n_neut, context_block
        )

        # ── Assemble PredictionCard ───────────────────────────────────────────
        direction_enum = DirectionEnum(direction)

        prediction_dict = {
            "ticker":         ticker,
            "direction":      direction_enum,
            "confidence":     confidence,
            "time_horizon":   TimeHorizonEnum.D7,
            "causal_chain":   causal_chain,
            "key_signals":    key_signals,
            "agent_consensus": AgentConsensus(up=n_bull, down=n_bear, neutral=n_neut),
            "simulation_id":  simulation_results["simulation_id"],
            "trigger_event_id": event_data.get("event_id_cnty"),
            "generated_at":   datetime.utcnow(),
            "contrarian_view": contrarian_view,
            "risk_factors":   risk_factors,
            # New fields (Upgrade 6)
            "confidence_method":       "weighted_variance_v2",
            "judge_verdict":           judge.get("verdict", "neutral"),
            "judge_confidence_modifier": judge.get("confidence_modifier", 0),
            "iron_ore_price":          market_ctx["iron_ore_price"],
            "iron_ore_change_pct":     market_ctx["iron_ore_change_pct"],
            "audusd_rate":             market_ctx["audusd_rate"],
            "audusd_change_pct":       market_ctx["audusd_change_pct"],
            "brent_price":             market_ctx["brent_price"],
            "ticker_price":            market_ctx["ticker_price"],
            "ticker_rsi":              market_ctx["ticker_rsi"],
            "trigger_event":           judge.get("trigger_event", ""),
            "cost_impact":             judge.get("cost_impact", ""),
            "revenue_impact":          judge.get("revenue_impact", ""),
            "demand_signal":           judge.get("demand_signal", ""),
            "sentiment_signal":        judge.get("sentiment_signal", ""),
            "data_freshness":          market_ctx["data_freshness"],
            # Bug Fix 5: data quality fields
            "data_quality":            market_ctx.get("data_quality"),
            "data_issues":             market_ctx.get("data_issues"),
            "show_data_warning":       market_ctx.get("show_data_warning"),
            # Fix 2: broad market warning + chain audit
            "market_warning":          simulation_results.get("market_warning"),
            "chain_override_flag":     simulation_results.get("chain_override_flag"),
            "slot_verdicts":           simulation_results.get("slot_verdicts"),
            # Fix 1: insufficient signal note
            "signal_note":             simulation_results.get("signal_note"),
            # Fix 4: blind judge + reconciler fields
            "override_flag":           simulation_results.get("reconciler_flag"),
            "blind_judge_verdict":     simulation_results.get("blind_judge_verdict"),
            "blind_judge_confidence":  simulation_results.get("blind_judge_confidence"),
            "blind_judge_reasoning":   simulation_results.get("blind_judge_reasoning"),
            "reconciler_flag":         simulation_results.get("reconciler_flag"),
            "reconciler_reasoning":    simulation_results.get("reconciler_reasoning"),
            # Fix 3: stale news dropped count
            "stale_news_dropped":      market_ctx.get("stale_news_dropped", 0),
            # Trend Momentum fields
            "trend_label":             market_ctx.get("trend_label"),
            "day_1_change":            market_ctx.get("day_1_change"),
            "day_5_change":            market_ctx.get("day_5_change"),
            "day_20_change":           market_ctx.get("day_20_change"),
            "consecutive_down_days":   market_ctx.get("consecutive_down_days"),
            "dist_from_52w_high_pct":  market_ctx.get("dist_from_52w_high_pct"),
            "ticker_volume_vs_avg":    market_ctx.get("ticker_volume_vs_avg"),
            # Anti-bias: persona distribution used
            "persona_distribution":    simulation_results.get("persona_distribution"),
        }

        prediction = PredictionCard(**prediction_dict)
        logger.info("Prediction report generated: %s %s %.0f%%",
                    ticker, direction, confidence * 100)
        return prediction

    async def _gen_contrarian_and_risks(
        self, ticker, ticker_info, event_data, direction, n_bull, n_bear, n_neut, context_block
    ) -> Tuple[Optional[str], Optional[List[str]]]:
        """Quick LLM call for contrarian view and risk factors only."""
        system = (
            "You are a risk analyst. Given simulation results, return ONLY valid JSON "
            "(no markdown): {\"contrarian_view\": \"one sentence\", \"risk_factors\": [\"...\", \"...\"]}"
        )
        user = (
            f"Ticker: {ticker} ({ticker_info.get('name', '')})\n"
            f"Direction: {direction} | Bull: {n_bull} Bear: {n_bear} Neutral: {n_neut}\n"
            f"Event: {event_data.get('notes', event_data.get('location', ''))[:300]}\n"
            f"{context_block[:500]}\n"
            f"Return the JSON with contrarian_view and 2-3 risk_factors."
        )
        try:
            resp = await self.llm_router.call_boost(system, user, session_id=f"{self.simulation_id}_risk")
            data = parse_json_response(resp)
            return data.get("contrarian_view"), data.get("risk_factors", [])
        except Exception as e:
            logger.warning("Contrarian/risk call failed: %s", e)
            return None, None


# ── Helpers ────────────────────────────────────────────────────────────────────

def _build_causal_chain(judge: Dict[str, Any], direction: str) -> List[CausalChainStep]:
    """Build 6-step structured causal chain from Judge output."""
    dir_arrow = "[UP]" if direction == "UP" else ("[DOWN]" if direction == "DOWN" else "[NEUTRAL]")

    steps_raw = [
        (1, "TRIGGER EVENT",        judge.get("trigger_event",   "No data — assumed neutral impact")),
        (2, "DIRECT COST IMPACT",   judge.get("cost_impact",     "No data — assumed neutral impact")),
        (3, "DIRECT REVENUE IMPACT",judge.get("revenue_impact",  "No data — assumed neutral impact")),
        (4, "DEMAND SIGNAL",        judge.get("demand_signal",   "No data — assumed neutral impact")),
        (5, "SENTIMENT SIGNAL",     judge.get("sentiment_signal","No data — assumed neutral impact")),
        (6, "NET CONCLUSION",       f"Overall direction: {direction} {dir_arrow} based on cost/revenue/demand/sentiment analysis"),
    ]

    # Reject predictions where more than 2 slots say "No data"
    no_data_count = sum(1 for _, _, val in steps_raw if "No data" in val)
    if no_data_count > 2:
        logger.warning("Causal chain has %d 'No data' slots — Judge may have failed", no_data_count)

    return [
        CausalChainStep(step=step, event=label, consequence=value)
        for step, label, value in steps_raw
    ]


def _build_key_signals(
    market_ctx: Dict[str, Any],
    n_bull: int, n_bear: int, n_neut: int,
    direction: str
) -> List[KeySignal]:
    """Build key signals from live market data."""
    signals = []

    # Iron ore signal
    iron_chg = market_ctx.get("iron_ore_change_pct", 0)
    signals.append(KeySignal(
        signal_type=SignalType.COMMODITY,
        description=f"Iron Ore 62% Fe: ${market_ctx.get('iron_ore_price', 'N/A')}/t | {'+' if iron_chg >= 0 else ''}{iron_chg}% today",
        impact="positive" if iron_chg > 0 else ("negative" if iron_chg < 0 else "neutral"),
        confidence=0.85,
    ))

    # AUD/USD signal
    audusd_chg = market_ctx.get("audusd_change_pct", 0)
    signals.append(KeySignal(
        signal_type=SignalType.MACRO,
        description=f"AUD/USD: {market_ctx.get('audusd_rate', 'N/A')} | {'+' if audusd_chg >= 0 else ''}{audusd_chg}% (USD-denominated revenue impact)",
        impact="negative" if audusd_chg > 0 else ("positive" if audusd_chg < 0 else "neutral"),
        confidence=0.80,
    ))

    # Technical signal — rsi may be None when AV key unavailable
    rsi  = market_ctx.get("ticker_rsi")   # None when unavailable
    macd = market_ctx.get("ticker_macd_signal", "NEUTRAL")
    tech_impact = "neutral"
    if rsi is not None and rsi < 30 or macd == "BULLISH_CROSS":
        tech_impact = "positive"
    elif rsi is not None and rsi > 70 or macd == "BEARISH_CROSS":
        tech_impact = "negative"
    rsi_display = f"RSI(14)={rsi}" if rsi is not None else "RSI=UNAVAILABLE"
    signals.append(KeySignal(
        signal_type=SignalType.MARKET_SENTIMENT,
        description=f"Technicals: {rsi_display} | MACD={macd} | Volume vs Avg={market_ctx.get('ticker_volume_vs_avg', 1.0)}x",
        impact=tech_impact,
        confidence=0.70,
    ))

    # Agent consensus signal
    total = n_bull + n_bear + n_neut
    dom_pct = max(n_bull, n_bear) / total * 100 if total > 0 else 0
    signals.append(KeySignal(
        signal_type=SignalType.MARKET_SENTIMENT,
        description=f"Agent consensus: {n_bull} bullish | {n_bear} bearish | {n_neut} neutral (dominant side: {dom_pct:.0f}%)",
        impact="positive" if direction == "UP" else ("negative" if direction == "DOWN" else "neutral"),
        confidence=round(abs(n_bull - n_bear) / total, 2) if total > 0 else 0.5,
    ))

    return signals


# ═══════════════════════════════════════════════════════════════════════════════
# Prediction log persistence (Upgrade 5a)
# ═══════════════════════════════════════════════════════════════════════════════

async def save_to_prediction_log(
    simulation_id: str,
    ticker: str,
    direction: str,
    confidence: float,
    primary_reason: str,
    market_ctx: Dict[str, Any],
) -> None:
    """Save prediction to prediction_log table (non-blocking)."""
    try:
        from database import get_db, init_db
        await init_db()
        async with get_db() as db:
            await db.execute(
                """INSERT OR REPLACE INTO prediction_log
                   (id, ticker, predicted_direction, confidence, predicted_at,
                    primary_reason,
                    iron_ore_at_prediction, audusd_at_prediction,
                    brent_at_prediction, bhp_price_at_prediction)
                   VALUES (?,?,?,?,?,?,?,?,?,?)""",
                (
                    simulation_id, ticker, direction.lower(),
                    confidence,
                    datetime.utcnow().isoformat(),
                    primary_reason[:500],
                    market_ctx.get("iron_ore_price"),
                    market_ctx.get("audusd_rate"),
                    market_ctx.get("brent_price"),
                    market_ctx.get("ticker_price"),
                )
            )
            await db.commit()
        logger.info("Saved %s to prediction_log", simulation_id)
    except Exception as e:
        logger.warning("prediction_log save failed (non-critical): %s", e)


# ═══════════════════════════════════════════════════════════════════════════════
# Legacy compatibility shim — used by routes/simulate.py
# ═══════════════════════════════════════════════════════════════════════════════

# routes/simulate.py imports Simulation and calls:
#   simulation.run_simulation(event_data, ticker, num_rounds)
#   simulation.generate_prediction_report(results)
# Both methods exist on the new Simulation class above — no changes needed in simulate.py


# ═══════════════════════════════════════════════════════════════════════════════
# Standalone test
# ═══════════════════════════════════════════════════════════════════════════════

async def main():
    print("\n" + "=" * 60)
    print("  MARKET ORACLE AI — SIMULATION ENGINE v2 TEST")
    print("=" * 60)

    sample_event = {
        'event_id_cnty': 'test_v2_001',
        'country': 'China',
        'location': 'Beijing',
        'event_type': 'Strategic developments',
        'fatalities': 0,
        'event_date': datetime.now().strftime('%Y-%m-%d'),
        'notes': 'China announces 15% reduction in iron ore import quotas from Australia citing trade dispute escalation'
    }

    llm_router = LLMRouter()
    simulation = Simulation(llm_router)

    results = await simulation.run_simulation(
        event_data=sample_event,
        ticker="BHP.AX",
        num_rounds=1,
    )

    prediction = await simulation.generate_prediction_report(results)

    print(f"\nTicker:     {prediction.ticker}")
    print(f"Direction:  {prediction.direction.value}")
    print(f"Confidence: {prediction.confidence:.1%}")
    print(f"Judge:      {prediction.judge_verdict} ({prediction.judge_confidence_modifier:+d}%)")
    print(f"\nAgent consensus: UP={results['n_bull']} DOWN={results['n_bear']} NEUTRAL={results['n_neut']}")
    print(f"\nCalc check (24B/0Bu/26N): {calculate_confidence(0, 24, 26):.3f} (expect ~0.230)")

    print(f"\nCausal Chain:")
    for step in prediction.causal_chain:
        print(f"  {step.step}. [{step.event}] {step.consequence[:80]}")

    print(f"\nMarket Snapshot:")
    print(f"  Iron Ore: ${prediction.iron_ore_price}/t ({prediction.iron_ore_change_pct:+.2f}%)")
    print(f"  AUD/USD:  {prediction.audusd_rate} ({prediction.audusd_change_pct:+.2f}%)")
    print(f"  Brent:    ${prediction.brent_price}/bbl")
    print(f"  RSI(14):  {prediction.ticker_rsi}")

    print("\n[OK] Simulation v2 test complete")


if __name__ == "__main__":
    asyncio.run(main())
